apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator: {}
    prometheusK8s: 
      retention: 24h
      externalLabels:
        region: eu
        environment: nonprod
      volumeClaimTemplate:
       spec:
         storageClassName: managed-premium
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          resources:
            requests:
              storage: 10Gi
    auth: {}
    nodeExporter: {}
    kubeStateMetrics: {}
