apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch
  namespace: openshift-operators-redhat
spec:
  channel: 'stable-5.x'
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace

#oc apply -f elasticsearch.yaml
#oc get csv