apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "istio-system"

generatorOptions:
  disableNameSuffixHash: true

resources:
  - istio-system-ns.yaml
  - smcp-v1.yaml
  - smmr.yaml